apiVersion: v1
kind: Pod
metadata:
  name: host-path-mount-pod
spec:
  containers:
  - name: host-path-container
    image: busybox:latest
    volumeMounts:
    - name: test-vol
      mountPath: /test
  volumes:
  - name: test-vol
    hostPath: 
      path: /test/data
      type: DirectoryOrCreate