kind: Pod
apiVersion: v1
metadata:
  name: the-pod
spec:
  containers:
  - name: the-container
    image: g1g1/py-kube:0.3
    command: ["bash"]
    args: ["-c", "echo started...; while true ; do sleep 1 ; done"]
    volumeMounts:
    - mountPath: "/mnt/data"
      name: pvc-1e86aaa6-671b-4aae-9dd1-94d9a72cec37
  volumes:
  - name: pvc-1e86aaa6-671b-4aae-9dd1-94d9a72cec37
    persistentVolumeClaim:
      claimName: some-pvc