partner-url=https://www.fedex.com
partner-key=1234




# kubectl create configmap full-file-map --from-file=./application.
properties --namespace configmap-test


# kubectl get configmaps --namespace configmap-test

# kubectl get configmap full-file-map -o yaml --namespace configmap-test

